name: cs2109s-ay2526s1
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.12.1
  - pip
  - numpy=1.26.3
  - pandas=2.1.4
  - scikit-learn=1.3.2
  - matplotlib=3.8.2
  - notebook=7.2
  - seaborn=0.13
  - timeout-decorator=0.5.0
  - pip: # There is no python 3.12 torchvision for macOS
    - --extra-index-url https://download.pytorch.org/whl/cpu
    - torch==2.3.0
    - torchvision==0.18.0